### ISSUE TITLE
Скласти додаткові інформаційні блоки

### ISSUE THREAD

**Issue by Bogdan-Bendziukov** [Bogdan-Bendziukov/homepage#4]
Можна зробити резюме менш формальним, додавши додаткові блоки, які містять корисну інформацію, але подають її в "розважальній" формі. Наприклад, що подобається і не подобається, сильні і слабкі сторони, перелік навиків чи хобі, інфографіка або ж інтерактивні модулі, тощо. Варто написати контент такого блоку раніше, ніж починати верстку, бо його розміри впливатимуть на розміщення елементів на сторінці.

**Comment by Bogdan-Lenz** [comment]
Люблю кататься на вельчике.
Обожаю рок / хардкор, хожу на концерты, концерт-туризм. Учусь играть на барабанах. 
Ну и конечно **I know H.T.M.L.**

**Comment by Bogdan-Bendziukov** [comment]
Кремниевая долина детектед
