### ISSUE TITLE
Скласти блок контактної інформації

### ISSUE THREAD

**Issue by Bogdan-Bendziukov** [Bogdan-Bendziukov/homepage#5]
Посилання на соцмережі (Facebook чи Instagram, тощо), номер телефону чи адреса електронної скриньки, тощо. Може не всі лінки в світі, а тільки ті, що дійсно доречні.

**Comment by Bogdan-Lenz** [comment]
Skype: barb0sss
FB: https://www.facebook.com/bogdan.bendziukov

**Comment by Bogdan-Lenz** [comment]
Telegram: hhtps://t.me/kyiv_in_me
E-mail: iam@bogdan.kyiv.ua
