### ISSUE TITLE
Скласти інтро

### ISSUE THREAD

**Issue by Bogdan-Bendziukov** [Bogdan-Bendziukov/homepage#6]
Скласти інтро (вступ), де в 2-4 реченнях описати, що замовник робить, що подобається робити, що хочеться робити краще, що важливо робити, тощо.

**Comment by Bogdan-Lenz** [comment]
Я занимаюсь разработкой сайтов на CMS Wordpress более 7 лет. Также разрабатываю плагины, виджеты, темы и прочие фичи для этого чудесного движка.
Конечно, я не стою на месте и надо прокачивать свои скиллы. Потому я хочу поступить в Binary Academy, чтобы быть топовым разработчиком.
