### ISSUE TITLE
Скласти таймлайн

### ISSUE THREAD

**Issue by Bogdan-Bendziukov** [Bogdan-Bendziukov/homepage#7]
Скласти список всіх (важливих) життєвих подій, визначних дат, досягнень, періодів, що дали приємний і неприємний досвід, тощо. В цьому конкретному випадку довгих списків не буває, натомість бувають погано згорнуті, тому пакуємо сюди все підряд, а про "лишні" події можна буде промовчати пізніше. Список повинен бути систематизованим і посортованим в такий спосіб, щоб читач швидко зрозумів "паттерн" і міг легко орієнтуватись в просторі і часі цього резюме.

**Comment by Bogdan-Lenz** [comment]
**1992**
```
let human = {
    name: "Bogdan",
    last_name: "Bendziukov".
    sex: "M",
    birth_date: "1992-07-30 08:50:27 GMT+3"
}
```
**1998**
`human.action = () => goToSchool(325)`

**2009**
`human.action = () => graduatedSchool(true)`
`human.action = () => goToUniversity('NAU')`

**2012**
`human.action = () => goToWork('freelance')`

**2015**
`human.action = () => graduatedUniversity(true, 'master')`

**Comment by Bogdan-Bendziukov** [comment]
Ну ок, я понял
